name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository with submodules
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SECPL_PULL_KEY }}
        submodules: 'recursive'
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'  
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn clean verify sonar:sonar -Pcoverage -Dsonar.login=${{secrets.SONAR_LOGIN}}
