name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true # 'recursive' 'true' or 'false'
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: maven-setings-action
      uses: s4u/maven-settings-action@v2.1.0
      with:
        servers: '[{"id": "MoMOT", "configuration": {"httpConfiguration": {"all": {"connectionTimeout": "120000", "readTimeout": "120000"}}}}]'
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn clean verify -fae -e sonar:sonar -Pcoverage -Dsonar.projectKey=gravity -Dsonar.login=${{secrets.SONAR_LOGIN}} -Dtycho.disableP2Mirrors=true --file pom.xml
